// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: grpc/hashtag/hashtag.proto

package hashtag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHashTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateHashTagRequest) Reset() {
	*x = CreateHashTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_hashtag_hashtag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHashTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHashTagRequest) ProtoMessage() {}

func (x *CreateHashTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_hashtag_hashtag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHashTagRequest.ProtoReflect.Descriptor instead.
func (*CreateHashTagRequest) Descriptor() ([]byte, []int) {
	return file_grpc_hashtag_hashtag_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHashTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateHashTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateHashTagResponse) Reset() {
	*x = CreateHashTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_hashtag_hashtag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHashTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHashTagResponse) ProtoMessage() {}

func (x *CreateHashTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_hashtag_hashtag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHashTagResponse.ProtoReflect.Descriptor instead.
func (*CreateHashTagResponse) Descriptor() ([]byte, []int) {
	return file_grpc_hashtag_hashtag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHashTagResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateHashTagResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_grpc_hashtag_hashtag_proto protoreflect.FileDescriptor

var file_grpc_hashtag_hashtag_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x2f, 0x68,
	0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x66, 0x6f,
	0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x22, 0x2a, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61,
	0x73, 0x68, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x32, 0x7f, 0x0a, 0x07, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x12, 0x74, 0x0a, 0x0d,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x12, 0x30, 0x2e,
	0x66, 0x6f, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x31, 0x2e, 0x66, 0x6f, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x66, 0x6f, 0x6c, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_hashtag_hashtag_proto_rawDescOnce sync.Once
	file_grpc_hashtag_hashtag_proto_rawDescData = file_grpc_hashtag_hashtag_proto_rawDesc
)

func file_grpc_hashtag_hashtag_proto_rawDescGZIP() []byte {
	file_grpc_hashtag_hashtag_proto_rawDescOnce.Do(func() {
		file_grpc_hashtag_hashtag_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_hashtag_hashtag_proto_rawDescData)
	})
	return file_grpc_hashtag_hashtag_proto_rawDescData
}

var file_grpc_hashtag_hashtag_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_hashtag_hashtag_proto_goTypes = []interface{}{
	(*CreateHashTagRequest)(nil),  // 0: fold.protobuf.grpc.hashtag.CreateHashTagRequest
	(*CreateHashTagResponse)(nil), // 1: fold.protobuf.grpc.hashtag.CreateHashTagResponse
}
var file_grpc_hashtag_hashtag_proto_depIdxs = []int32{
	0, // 0: fold.protobuf.grpc.hashtag.Hashtag.CreateHashTag:input_type -> fold.protobuf.grpc.hashtag.CreateHashTagRequest
	1, // 1: fold.protobuf.grpc.hashtag.Hashtag.CreateHashTag:output_type -> fold.protobuf.grpc.hashtag.CreateHashTagResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_hashtag_hashtag_proto_init() }
func file_grpc_hashtag_hashtag_proto_init() {
	if File_grpc_hashtag_hashtag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_hashtag_hashtag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHashTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_hashtag_hashtag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHashTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_hashtag_hashtag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_hashtag_hashtag_proto_goTypes,
		DependencyIndexes: file_grpc_hashtag_hashtag_proto_depIdxs,
		MessageInfos:      file_grpc_hashtag_hashtag_proto_msgTypes,
	}.Build()
	File_grpc_hashtag_hashtag_proto = out.File
	file_grpc_hashtag_hashtag_proto_rawDesc = nil
	file_grpc_hashtag_hashtag_proto_goTypes = nil
	file_grpc_hashtag_hashtag_proto_depIdxs = nil
}
